name: Code Check

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  validate-format:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Fetch submodules
        run: git submodule update --init --recursive

      - name: Install clang-format
        run: |
          sudo apt-get update -y

          # see https://apt.llvm.org/
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 18
          
          sudo apt-get install -y clang-format-18

      - name: Fetch & install RISC-V GNU Compiler Toolchain
        run: |
          curl -Lo riscv32-glibc-ubuntu-22.04-nightly.tar.gz 'https://github.com/riscv-collab/riscv-gnu-toolchain/releases/download/2023.06.09/riscv32-glibc-ubuntu-22.04-nightly-2023.06.09-nightly.tar.gz'
          tar -xf riscv32-glibc-ubuntu-22.04-nightly.tar.gz
          echo "${PWD}/riscv/bin" >> $GITHUB_PATH

      - name: Run clang-format
        run: |
          make clang-format-check


  static-analysis:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Fetch submodules
        run: git submodule update --init --recursive

      - name: Install clang-tidy
        run: |
          sudo apt-get update -y

          # see https://apt.llvm.org/
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 18

          sudo apt-get install -y clang-tidy-18

      - name: Fetch & install RISC-V GNU Compiler Toolchain
        run: |
          curl -Lo riscv32-glibc-ubuntu-22.04-nightly.tar.gz 'https://github.com/riscv-collab/riscv-gnu-toolchain/releases/download/2023.06.09/riscv32-glibc-ubuntu-22.04-nightly-2023.06.09-nightly.tar.gz'
          tar -xf riscv32-glibc-ubuntu-22.04-nightly.tar.gz
          echo "${PWD}/riscv/bin" >> $GITHUB_PATH

      - name: Run clang-tidy
        run: |
          make clang-tidy-check
